-- size of our actual window
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

-- size we're trying to emulate with push
VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144

ADVENTURER_WIDTH = 50
ADVENTURER_HEIGHT = 37

ADVENTURER_MAX_RUN_SPEED = 50
ADVENTURER_MAX_SPRINT_SPEED = 100
ADVENTURER_MAX_CROUCH_WALK_SPEED = 25

ADVENTURER_ACCELERATION = 180
ADVENTURER_DECELERATION = 180
ADVENTURER_SLIDE_DECELERATION = 15
ADVENTURER_MAX_JUMP_VELOCITY = -150
ADVENTURER_MIN_JUMP_VELOCITY = -300

FRICTION = 30

GRAVITY = 7